- name: "Optional Python packages"
  dnf: "name={{ item }}  state=present"
  with_items:
    - python3-psycopg2

- name: Create disk partition on /dev/sdb for data
  parted:
    device: /dev/sdb
    number: 1
    state: present
    fs_type: xfs
          
- name: Create a xfs filesystem on /dev/sdb1 for data
  filesystem:
    fstype: xfs
    dev: /dev/sdb1

- name: Create directory for postgresdb
  command: mkdir /var/lib/pgsql

- name: Create mount point for Postgres
  file:
  path: "{{ mount_point }}"
    #state: directory
    #owner: postgres
    #group: postgres
    #mode: '0700'

- name: Mount new partition
  mount:
    path: "{{ mount_point }}"
    src: "{{ new_partition }}"
    fstype: xfs
    state: mounted
    
- name: "postgres packages Installation"
  dnf: "name={{ item }} state=present"
  with_items:
    - postgresql
    - postgresql-server


- name: "Check if PostgreSQL is initialized"
  ansible.builtin.stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data

- name: "Initializing PostgreSQL"
  shell: "postgresql-setup initdb"
  when: not postgres_data.stat.exists
 
- name: "Start and enable services"
  service: "name={{ item }} state=started enabled=yes"
  with_items:
    - postgresql

- name: Set password for postgres user
  postgresql_user:
    db: postgres
      user: postgres
      password: "{{ postgres_password }}"
    become_user: postgres          

- name: Change password for postgres user
  user:
    name: postgres
    password: "{{ postgres_password | password_hash('sha512') }}"
