- name: "Optional Python packages"
  dnf: "name={{ item }}  state=present"
  with_items:
    - python3-psycopg2

- name: Create disk partition on /dev/sdb for data
  parted:
    device: /dev/sdb
    number: 1
    state: present
    fs_type: xfs
          
- name: Create a xfs filesystem on /dev/sdb1 for data
  filesystem:
    fstype: xfs
    dev: /dev/sdb1


- name: create mount directory
  file:
    path: '/var/lib/'
    state: directory
    mode: '0755'
  with_items:
    - pgsql

- name: Mount new partition
  mount:
    path: '/var/lib/pgsql'
    src: '/dev/sdb1'
    fstype: xfs
    state: mounted
    
- name: "postgres packages Installation"
  dnf: "name={{ item }} state=present"
  with_items:
    - postgresql
    - postgresql-server


- name: "Check if PostgreSQL is initialized"
  ansible.builtin.stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data

- name: "Initializing PostgreSQL"
  shell: "postgresql-setup initdb"
  when: not postgres_data.stat.exists
 
- name: "Start and enable services"
  service: "name={{ item }} state=started enabled=yes"
  with_items:
    - postgresql

- name: Set password for postgres user
  postgresql_user:
    db: postgres
    user: postgres
    password: "{{ postgrespass }}"
  become_user: postgres

- name: Change password for postgres user
  user:
    name: postgres
    password: "{{ postgrespass | password_hash('sha512') }}"

- name: "App database Creation"
  postgresql_db:
    state: present
    name: "{{ postgres_db_name }}"
  become: yes
  become_user: postgres

- name: "database user creation"
  postgresql_user:
    state: present
    name: "{{ postgresdb_user }}"
    password: "{{ postgrespass }}"
  become: yes
  become_user: postgres

- name: "database  user access to app db"
  postgresql_privs:
    type: database
    database: "{{ postgres_db_name }}"
    roles: "{{ postgresdb_user }}"
    grant_option: yes
    privs: all
  become: yes
  become_user: postgres

- name: check permission
  ansible.builtin.file:
    path: "{{ mount_point }}"
    owner: "postgres"
    group: "postgres"
    mode: '0700'
