yumrepo_server:         "10.21.152.167"
ntp_server: ""
node_exporter_version: "1.5.0"
mysql_exporter_version: "0.14.0"
postgres_exporter_version: "0.12.0"
win_node_exporter_version: "0.20.0"
sql_exporter_version: "0.5"
node_exporter_bin: /usr/local/bin/node_exporter
mysql_exporter_bin: /usr/local/bin/mysqld_exporter
postgres_exporter_bin: /usr/local/bin/
exporter_user: prometheus
exporter_group: "prometheus"
node_exporter_dir_conf: /etc/node_exporter
mysql_exporter_dir_conf: /etc/mysql_exporter
postgres_exporter_dir_conf: /etc/postgres_exporter
sqlpass: ""
postgrespass: ""
postgres_db_name: postgresdbapp
postgresdb_user: dbuser
