- name: Add a Veeam Backup Repository
  hosts: veeam_setup
  tasks:
    - name: Execute multiline PowerShell script
      ansible.builtin.debug:
        msg: 
         The Windows Repo Server is {{ hostvars.windows_repo_server.ansible_host }}

    - name: Create directory 
      ansible.windows.win_powershell:
        script: |
          New-Item -Path "C:\PureStorageBackup" -ItemType Directory 

    - name: Execute multiline PowerShell script
      win_shell: |
        # Import the Veeam PowerShell module
        Add-PSSnapin VeeamPSSnapIn -ErrorAction SilentlyContinue
        Add-VBRWinServer -Name "{{ hostvars.windows_repo_server.ansible_host }}" -User Administrator -Password "VMware1!" 
        $server = Get-VBRServer -Name "{{ hostvars.windows_repo_server.ansible_host }}"
        Add-VBRBackupRepository -Name "{{ hostvars.windows_repo_server.ansible_host }}" -Server $server -Folder "c:\PureStorageBackup" -Type WinLocal 
      args:
        executable: powershell




