- name: Install Windows Veeam Proxy Server 
  hosts: veeam-server
  tasks:
    - name: print message
      ansible.builtin.debug:
        msg: "Veeam Windows Proxy Server is {{ veeam_windows_proxy_server }}"  

    - name:  Load Veeam PowerShell Snap-In 
      ansible.windows.win_powershell:
        script: |
          Import-Module Veeam.Backup.PowerShell 

    - name: Add Credentails for Windows Veeam Proxy Server
      ansible.windows.win_powershell:
        script: |
          Add-VBRWinServer -Name {{ veeam_windows_proxy_server }} -Password {{ ansible_password }} -User {{ ansible_user }}  -Description "Veeam Windows Proxy Server"

    - name: Add Windows Veeam Proxy Server
      ansible.windows.win_powershell:
        script: |
          Add-VBRVProxy -Server {{ veeam_windows_proxy_server }}
