- name: Restore NFS share from Backup
  hosts: veeam-server
  vars:
    nfs_share_restore_point: "10.21.122.33:/test-export"
    restore_path: "C:\\Restore\\test-export"
  tasks:
    - name: Debug restore operation
      ansible.builtin.debug:
        msg: Initiating restore for NFS Share {{ nfs_share_restore_point }} to {{ restore_path }}

    - name: Execute multiline PowerShell script for restore
      win_shell: |
        Add-PSSnapin VeeamPSSnapIn -ErrorAction SilentlyContinue

        $backupJob = Get-VBRBackup | Where-Object { $_.Name -eq "Backup {{ nfs_share_restore_point }}" }

        if ($backupJob) {
            $restorePoint = Get-VBRRestorePoint -Backup $backupJob | Sort-Object CreationTime -Descending | Select-Object -First 1

            if ($restorePoint) {
                $restoreSession = Start-VBRNASRestore -RestorePoint $restorePoint -TargetPath "{{ restore_path }}" -RestoreMode "Copy"

                while ($restoreSession.State -eq "Working") {
                    Start-Sleep -Seconds 10
                    Write-Host "Restore in progress..."
                }

                if ($restoreSession.State -eq "Success") {
                    Write-Host "Restore completed successfully."
                } else {
                    Write-Host "Restore failed. State: $($restoreSession.State)"
                }
            } else {
                Write-Host "No restore point found for the backup job."
            }
        } else {
            Write-Host "Backup job not found."
        }
      args:
        executable: powershell
