
---

# - name: create DB
#   win_command: sqlcmd -i "C:\test.sql"
#   register: sqlcmd_out

# - name: print result
#   debug:
#     var: sqlcmd_out

# - name: Update auth option
#   win_command: sqlcmd -i "C:\test1.sql"
#   register: sqlcmd2_out

# - name: print result
#   debug:
#     var: sqlcmd2_out

# - name: restart MSSQL
#   ansible.windows.win_service:
#     name: MSSQLSERVER
#     state: restarted

- name: Run executable using argv and have win_command escape the spaces as needed
  ansible.windows.win_shell: C:\Program Files\Pure Storage\D.O.E.S\DOES.Cli --engine data  --function add --hostname localhost --databasetype MicrosoftSQL --databasename db1 --amount 1 --unit  Terabytes --username admin --password VMware1! --numberofthreads 8 --WithIndexes --folder \\10.21.152.167\packages\datafiles
