
---

# - name: create DB
#   win_command: sqlcmd -i "C:\test.sql"
#   register: sqlcmd_out

# - name: print result
#   debug:
#     var: sqlcmd_out

- name: Update auth option
  win_command: sqlcmd -i "C:\test2.sql"
  register: sqlcmd2_out

- name: print result
  debug:
    var: sqlcmd2_out

- name: restart MSSQL
  ansible.windows.win_command:
    cmd: net restart MSSQLSERVER

# - name: Run executable using argv and have win_command escape the spaces as needed
#   ansible.windows.win_command:
#     # When using argv, each entry is quoted in the module
#     argv:
#     - c:\Program Files\Pure Storage\D.O.E.S\DOES.Cli 
#     - --engine data 
#     - --function add 
#     - --hostname localhost 
#     - --databasetype MicrosoftSQL 
#     - --databasename db8 
#     - --amount 1 
#     - --unit  Terabytes 
#     - --username admin 
#     - --password VMware1! 
#     - --numberofthreads 8 
#     - --WithIndexes 
#     - --folder c:\datafiles
